### ISSUE TITLE
Tree view lists no files or folders after switching to a project in Atom 1.17.0-beta

### ISSUE THREAD

**Issue by sentience** [mehcode/atom-project-util#2]
Per danielbrodin/atom-project-manager#333, this package's support for switching projects in the existing window appears to be broken in Atom 1.17.0-beta, where the Tree View goes blank (lists no files or folders) whenever this is attempted.

**Comment by oldCoderException** [comment]
Issue remains in released version.  Things work if you open projects in a new window but not if you open them in the same window.  I much prefer the "one window" approach so I'll likely revert to version 1.16 until this is fixed.  I noticed the same behaviour in another project manager package, project-plus.

**Comment by mehcode** [comment]
Definitely a bug. I'll try and get some time to look at it but if anyone has a solution, please open a PR.

**Comment by toropanov** [comment]
Hope it would help for fixing
https://github.com/xream/atom-project-neue

**Comment by bbodine1** [comment]
A few items that may help figuring this out: 

Per the atom 1.17 change log post --

> Also check out this tree-view PR for an example of converting a panel to a dock item. One
> major thing worth noting is that panes and items within docks are now included in various
> global workspace methods such as getActivePaneItem, observeActivePane, etc. If you
> want to limit your scope to just the center of the workspace as was the case before docks
> existed, you’ll need to interact with the new WorkspaceCenter class, available via
> atom.workspace.getCenter().

Link to the PR that added the treeview into a dock:
https://github.com/atom/tree-view/pull/1056/files

**Comment by mehcode** [comment]
Fixed and released as v4.1.0

**Comment by mehcode** [comment]
For future reference.. 

This had nothing to do with the switch to docks. Props on Atom for not breaking backwards compat there.

I'm using a few private APIs to make this package work so there is no guarantee this package will work when Atom has a new version. Apparently project state is no longer silently replaced. Project state needs to be explicitly destroyed before another project can be loaded.

https://github.com/mehcode/atom-project-util/blob/master/index.js#L154-L160

**Comment by bbodine1** [comment]
@mehcode Thanks for all you've done to help Atom Project Manager. This package is one of the main reasons that I haven't switched back to sublime. Appreciate you putting the effort into making it great.
