### ISSUE TITLE
Why is 'find-and-replace' package reloaded?

### ISSUE THREAD

**Issue by marcofugaro** [mehcode/atom-project-util#5]
I am referring to these lines

https://github.com/mehcode/atom-project-util/blob/a35f998319b316d155850405daf29d0a358d2e74/index.js#L215-L217

They are responsible for the bug [#356](https://github.com/danielbrodin/atom-project-manager/issues/356) and [#339](https://github.com/danielbrodin/atom-project-manager/issues/339) of the package `atom-project-plus`. Removing them fixes the issues.

I also found [this related issue](https://github.com/mehcode/atom-project-plus/issues/98) of `atom-project-plus` and it looks like the issue on `find-and-replace` has been resolved?

I think that code is obsolete and could be removed, please answer as we don't know why was it put there in the first place.

**Comment by mehcode** [comment]
Likely just a hack for an old version of Atom got outdated. I'll accept a PR to remove those lines.

**Comment by marcofugaro** [comment]
Sure thing! https://github.com/mehcode/atom-project-util/pull/6
Please publish a new version!

**Comment by mehcode** [comment]
Done in 4.2.0
